# Generated by Django 3.1.7 on 2025-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задача'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='task',
            name='repeating_days',
        ),
        migrations.AddField(
            model_name='task',
            name='repeating_date',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
