# Generated by Django 3.1.7 on 2025-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20250414_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeating_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
