# Generated by Django 2.2.14 on 2021-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211124_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('profession', models.CharField(choices=[('Инженер', 'Инженер'), ('Ученый', 'Ученый'), ('Психолог', 'Психолог'), ('Другая', 'Другая')], max_length=9, verbose_name='Профессия')),
                ('i_work_nasa', models.BooleanField(default=False, verbose_name='Я работал в Nasa')),
                ('file', models.FileField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявка',
            },
        ),
    ]
