# Generated by Django 2.2.14 on 2022-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211214_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrvacApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ваше имя')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявка ИРВАС',
            },
        ),
    ]
