# Generated by Django 2.2.14 on 2022-01-06 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_irvacapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='irvacapply',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата заявки'),
            preserve_default=False,
        ),
    ]
