# Generated by Django 2.2.14 on 2022-01-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_irvacapply_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrvacFullApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100, verbose_name='Форма балкона')),
                ('width', models.CharField(max_length=100, verbose_name='Ширина')),
                ('height', models.CharField(max_length=100, verbose_name='Высота')),
                ('type', models.CharField(max_length=100, verbose_name='Тип остекления')),
                ('profile', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Ваше имя')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявка ИРВАС замерщик',
            },
        ),
    ]
