# Generated by Django 2.2.14 on 2022-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_irvacfullapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irvacfullapply',
            name='profile',
            field=models.CharField(choices=[('Холодное', 'Холодное'), ('Теплое', 'Теплое')], max_length=9, verbose_name='Тип остекления'),
        ),
    ]
