# Generated by Django 2.2.14 on 2022-03-06 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-dt',), 'verbose_name': 'Запись', 'verbose_name_plural': 'Запись'},
        ),
        migrations.AddField(
            model_name='todo',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
